name = "cf/trees"
version = "0.0.1"
licences = ["MPL 2.0"]
description = "Merkle Tree in Aiken."

dependencies = [
    { name = "aiken-lang/stdlib", version = "a6bbc331fdc460e5170c4d28b48e69712752d985", source = "github" }
]
